package com.swapnillengure.contrycodepickerlibrary;
public class Country<myListData> {
    public static CountryData[] myListData = new CountryData[]{
            new CountryData("Afghanistan", R.drawable.flag_afghanistan, "93"),
            new CountryData("Antigua and Barbuda", R.drawable.flag_antigua_and_barbuda, "1"),
            new CountryData("Anguilla", R.drawable.flag_anguilla, "1"),
            new CountryData("Albania", R.drawable.flag_albania, "355"),
            new CountryData("Armenia", R.drawable.flag_armenia, "374"),
            new CountryData("Angola", R.drawable.flag_angola, "244"),
            new CountryData("Antarctica", R.drawable.flag_antarctica, "672"),
            new CountryData("Argentina", R.drawable.flag_argentina, "54"),
            new CountryData("American Samoa", R.drawable.flag_american_samoa, "1"),
            new CountryData("Austria", R.drawable.flag_austria, "43"),
            new CountryData("Australia", R.drawable.flag_australia, "61"),
            new CountryData("Aruba", R.drawable.flag_aruba, "297"),
            new CountryData("Åland Islands", R.drawable.flag_aland, "358"),
            new CountryData("Azerbaijan", R.drawable.flag_azerbaijan, "994"),
            new CountryData("Bosnia And Herzegovina", R.drawable.flag_bosnia, "387"),
            new CountryData("Barbados", R.drawable.flag_barbados, "1"),
            new CountryData("Bangladesh", R.drawable.flag_bangladesh, "880"),
            new CountryData("Belgium", R.drawable.flag_belgium, "32"),
            new CountryData("Burkina Faso", R.drawable.flag_burkina_faso, "226"),
            new CountryData("Bulgaria", R.drawable.flag_bulgaria, "359"),
            new CountryData("Bahrain", R.drawable.flag_bahrain, "973"),
            new CountryData("Burundi", R.drawable.flag_burundi, "257"),
            new CountryData("Benin", R.drawable.flag_benin, "229"),
            new CountryData("Saint Barthélemy", R.drawable.flag_saint_barthelemy, "590"),
            new CountryData("Bermuda", R.drawable.flag_bermuda, "1"),
            new CountryData("Brunei Darussalam", R.drawable.flag_brunei, "673"),
            new CountryData("Bolivia", R.drawable.flag_bolivia, "591"),
            new CountryData("Brazil", R.drawable.flag_brazil, "55"),
            new CountryData("Bahamas", R.drawable.flag_bahamas, "1"),
            new CountryData("Bhutan", R.drawable.flag_bhutan, "975"),
            new CountryData("Botswana", R.drawable.flag_botswana, "267"),
            new CountryData("Belarus", R.drawable.flag_belarus, "375"),
            new CountryData("Belize", R.drawable.flag_belgium, "501"),
            new CountryData("Canada", R.drawable.flag_canada, "1"),
            new CountryData("Cocos", R.drawable.flag_cocos, "61"),
            new CountryData("Congo", R.drawable.flag_republic_of_the_congo, "243"),
            new CountryData("Central African Republic", R.drawable.flag_central_african_republic, "236"),
            new CountryData("Switzerland", R.drawable.flag_swaziland, "41"),
            new CountryData("Côte D'ivoire", R.drawable.flag_cote_divoire, "225"),
            new CountryData("Cook Islands", R.drawable.flag_cook_islands, "682"),
            new CountryData("Chile", R.drawable.flag_chile, "56"),
            new CountryData("Cameroon", R.drawable.flag_cameroon, "237"),
            new CountryData("China", R.drawable.flag_china, "86"),
            new CountryData("Colombia", R.drawable.flag_colombia, "57"),
            new CountryData("Costa Rica", R.drawable.flag_costa_rica, "506"),
            new CountryData("Cuba", R.drawable.flag_cuba, "53"),
            new CountryData("Cape Verde", R.drawable.flag_cape_verde, "238"),
            new CountryData("Curaçao", R.drawable.flag_curacao, "599"),
            new CountryData("Christmas Island", R.drawable.flag_christmas_island, "61"),
            new CountryData("Cyprus", R.drawable.flag_cyprus, "357"),
            new CountryData("Czech Republic", R.drawable.flag_czech_republic, "420"),
            new CountryData("Germany", R.drawable.flag_germany, "49"),
            new CountryData("Djibouti", R.drawable.flag_djibouti, "253"),
            new CountryData("Denmark", R.drawable.flag_denmark, "45"),

            new CountryData("Dominica", R.drawable.flag_dominica, "1"),
            new CountryData("Algeria", R.drawable.flag_algeria, "213"),
            new CountryData("Ecuador", R.drawable.flag_ecuador, "593"),
            new CountryData("Estonia", R.drawable.flag_estonia, "372"),
            new CountryData("Egypt", R.drawable.flag_egypt, "20"),
            new CountryData("Eritrea", R.drawable.flag_eritrea, "291"),
            new CountryData("Spain", R.drawable.flag_spain, "34"),
            new CountryData("Ethiopia", R.drawable.flag_ethiopia, "241"),
            new CountryData("Finland", R.drawable.flag_finland, "358"),
            new CountryData("Fiji", R.drawable.flag_fiji, "679"),
            new CountryData("Falkland", R.drawable.flag_falkland_islands, "500"),
            new CountryData("Micronesia", R.drawable.flag_micronesia, "691"),
            new CountryData("Faroe Islands", R.drawable.flag_faroe_islands, "298"),
            new CountryData("France", R.drawable.flag_france, "33"),
            new CountryData("Gabon", R.drawable.flag_gabon, "241"),
            new CountryData("United Kingdom", R.drawable.flag_united_kingdom, "44"),
            new CountryData("Grenada", R.drawable.flag_grenada, "1"),
            new CountryData("Georgia", R.drawable.flag_georgia, "995"),
            new CountryData("French Guyana", R.drawable.flag_french_polynesia, "594"),
            new CountryData("Guernsey", R.drawable.flag_guernsey, "44"),
            new CountryData("Ghana", R.drawable.flag_ghana, "233"),
            new CountryData("Gibraltar", R.drawable.flag_gibraltar, "350"),
            new CountryData("Greenland", R.drawable.flag_greenland, "299"),
            new CountryData("Gambia", R.drawable.flag_gambia, "220"),
            new CountryData("Guinea", R.drawable.flag_guinea, "224"),
            new CountryData("Guadeloupe", R.drawable.flag_guadeloupe, "590"),
            new CountryData("Equatorial Guinea", R.drawable.flag_equatorial_guinea, "240"),
            new CountryData("Greece", R.drawable.flag_greece, "30"),
            new CountryData("Guatemala", R.drawable.flag_guatemala, "502"),
            new CountryData("Guam", R.drawable.flag_guam, "1"),
            new CountryData("Guinea-bissau", R.drawable.flag_guinea, "245"),
            new CountryData("Guyana", R.drawable.flag_guyana, "592"),
            new CountryData("Hong Kong", R.drawable.flag_hong_kong, "852"),
            new CountryData("Honduras", R.drawable.flag_honduras, "504"),
            new CountryData("Croatia", R.drawable.flag_croatia, "385"),
            new CountryData("Haiti", R.drawable.flag_haiti, "509"),
            new CountryData("Hungary", R.drawable.flag_hungary, "36"),
            new CountryData("Indonesia", R.drawable.flag_indonesia, "62"),
            new CountryData("Ireland", R.drawable.flag_ireland, "353"),
            new CountryData("Israel", R.drawable.flag_israel, "972"),
            new CountryData("Isle Of Man", R.drawable.flag_isleof_man, "44"),
            new CountryData("Iceland", R.drawable.flag_iceland, "354"),
            new CountryData("India", R.drawable.flag_india, "91"),
            new CountryData("Iraq", R.drawable.flag_iraq, "964"),
            new CountryData("Iran", R.drawable.flag_iran, "98"),
            new CountryData("Italy", R.drawable.flag_italy, "39"),
            new CountryData("Jersey", R.drawable.flag_jersey, "44"),
            new CountryData("Jamaica", R.drawable.flag_jamaica, "1"),
            new CountryData("Jordan", R.drawable.flag_jordan, "962"),
            new CountryData("Japan", R.drawable.flag_japan, "81"),
            new CountryData("Kenya", R.drawable.flag_kenya, "254"),
            new CountryData("Kyrgyzstan", R.drawable.flag_kyrgyzstan, "996"),
            new CountryData("Cambodia", R.drawable.flag_cambodia, "855"),
            new CountryData("Kiribati", R.drawable.flag_kiribati, "686"),
            new CountryData("Comoros", R.drawable.flag_comoros, "269"),
            new CountryData("Saint Kitts and Nevis", R.drawable.flag_saint_kitts_and_nevis, "1"),
            new CountryData("North Korea", R.drawable.flag_north_korea, "850"),
            new CountryData("South Korea", R.drawable.flag_south_korea, "82"),
            new CountryData("Kuwait", R.drawable.flag_kuwait, "865"),
            new CountryData("Cayman Islands", R.drawable.flag_cayman_islands, "1"),
            new CountryData("Kazakhstan", R.drawable.flag_kazakhstan, "7"),
            new CountryData("Lao People's Democratic Republic", R.drawable.flag_laos, "856"),
            new CountryData("Lebanon", R.drawable.flag_lebanon, "961"),
            new CountryData("Saint Lucia", R.drawable.flag_saint_lucia, "1"),
            new CountryData("Liechtenstein", R.drawable.flag_liechtenstein, "423"),
            new CountryData("Sri Lanka", R.drawable.flag_sri_lanka, "94"),
            new CountryData("Liberia", R.drawable.flag_liberia, "231"),
            new CountryData("Lesotho", R.drawable.flag_lesotho, "266"),
            new CountryData("Lithuania", R.drawable.flag_lithuania, "370"),
            new CountryData("Luxembourg", R.drawable.flag_luxembourg, "352"),
            new CountryData("Latvia", R.drawable.flag_latvia, "371"),
            new CountryData("Libya", R.drawable.flag_libya, "218"),
            new CountryData("Morocco", R.drawable.flag_morocco, "212"),
            new CountryData("Monaco", R.drawable.flag_monaco, "377"),
            new CountryData("Moldova, Republic Of", R.drawable.flag_moldova, "373"),
            new CountryData("Montenegro", R.drawable.flag_of_montenegro, "382"),
            new CountryData("Saint Martin", R.drawable.flag_saint_martin, "590"),
            new CountryData("Madagascar", R.drawable.flag_madagascar, "261"),
            new CountryData("Marshall Islands", R.drawable.flag_marshall_islands, "692"),
            new CountryData("Macedonia", R.drawable.flag_macedonia, "389"),
            new CountryData("Mali", R.drawable.flag_mali, "223"),
            new CountryData("Myanmar", R.drawable.flag_myanmar, "95"),
            new CountryData("Myanmar", R.drawable.flag_myanmar, "976"),
            new CountryData("Macau", R.drawable.flag_macao, "853"),
            new CountryData("Northern Mariana Islands", R.drawable.flag_northern_mariana_islands, "1"),
            new CountryData("Martinique", R.drawable.flag_martinique, "596"),
            new CountryData("Mauritania", R.drawable.flag_mauritania, "222"),
            new CountryData("Montserrat", R.drawable.flag_montserrat, "1"),
            new CountryData("Malta", R.drawable.flag_malta, "356"),
            new CountryData("Mauritius", R.drawable.flag_mauritius, "230"),
            new CountryData("Maldives", R.drawable.flag_maldives, "960"),
            new CountryData("Malawi", R.drawable.flag_malawi, "265"),
            new CountryData("Mexico", R.drawable.flag_mexico, "52"),
            new CountryData("Malaysia", R.drawable.flag_malaysia, "60"),
            new CountryData("Mozambique", R.drawable.flag_mozambique, "258"),
            new CountryData("Namibia", R.drawable.flag_namibia, "264"),
            new CountryData("New Caledonia", R.drawable.flag_new_caledonia, "687"),
            new CountryData("Niger", R.drawable.flag_niger, "227"),
            new CountryData("Norfolk Islands", R.drawable.flag_norfolk_island, "672"),
            new CountryData("Nigeria", R.drawable.flag_nigeria, "234"),
            new CountryData("Nicaragua", R.drawable.flag_nicaragua, "505"),
            new CountryData("Netherlands", R.drawable.flag_netherlands, "31"),
            new CountryData("Norway", R.drawable.flag_norway, "47"),
            new CountryData("Nepal", R.drawable.flag_nepal, "977"),
            new CountryData("Nauru", R.drawable.flag_nauru, "674"),
            new CountryData("Niue", R.drawable.flag_niue, "683"),
            new CountryData("New Zealand", R.drawable.flag_new_zealand, "64"),
            new CountryData("Oman", R.drawable.flag_oman, "968"),
            new CountryData("Panama", R.drawable.flag_panama, "507"),
            new CountryData("Peru", R.drawable.flag_peru, "51"),
            new CountryData("French Polynesia", R.drawable.flag_french_polynesia, "689"),
            new CountryData("Papua New Guinea", R.drawable.flag_papua_new_guinea, "675"),
            new CountryData("Philippines", R.drawable.flag_philippines, "63"),
            new CountryData("Pakistan", R.drawable.flag_pakistan, "92"),
            new CountryData("Poland", R.drawable.flag_poland, "48"),
            new CountryData("Saint Pierre And Miquelon", R.drawable.flag_saint_pierre, "508"),
            new CountryData("Pitcairn Islands", R.drawable.flag_pitcairn_islands, "870"),
            new CountryData("Puerto Rico", R.drawable.flag_puerto_rico, "1"),
            new CountryData("Palestine", R.drawable.flag_palestine, "970"),
            new CountryData("Portugal", R.drawable.flag_portugal, "351"),
            new CountryData("Palau", R.drawable.flag_palau, "680"),
            new CountryData("Paraguay", R.drawable.flag_paraguay, "595"),
            new CountryData("Qatar", R.drawable.flag_qatar, "974"),
            new CountryData("Réunion", R.drawable.flag_soviet_union, "262"),
            new CountryData("Romania", R.drawable.flag_romania, "40"),
            new CountryData("Serbia", R.drawable.flag_serbia, "381"),
            new CountryData("Russian Federation", R.drawable.flag_russian_federation, "7"),
            new CountryData("Rwanda", R.drawable.flag_rwanda, "250"),
            new CountryData("Saudi Arabia", R.drawable.flag_saudi_arabia, "966"),
            new CountryData("Solomon Islands", R.drawable.flag_soloman_islands, "677"),
            new CountryData("Seychelles", R.drawable.flag_seychelles, "248"),
            new CountryData("Sudan", R.drawable.flag_sudan, "249"),
            new CountryData("Sweden", R.drawable.flag_sweden, "46"),
            new CountryData("Singapore", R.drawable.flag_singapore, "65"),
            new CountryData("Saint Helena, Ascension And Tristan Da Cunha", R.drawable.flag_saint_helena, "290"),
            new CountryData("Slovenia", R.drawable.flag_slovenia, "386"),
            new CountryData("Slovakia", R.drawable.flag_slovakia, "421"),
            new CountryData("Sierra Leone", R.drawable.flag_sierra_leone, "232"),
            new CountryData("San Marino", R.drawable.flag_san_marino, "378"),
            new CountryData("Senegal", R.drawable.flag_senegal, "221"),
            new CountryData("Somalia", R.drawable.flag_somalia, "252"),
            new CountryData("Suriname", R.drawable.flag_suriname, "597"),
            new CountryData("South Sudan", R.drawable.flag_south_sudan, "211"),
            new CountryData("Sao Tome And Principe", R.drawable.flag_sao_tome_and_principe, "239"),
            new CountryData("El Salvador", R.drawable.flag_el_salvador, "503"),
            new CountryData("Sint Maarten", R.drawable.flag_saint_martin, "1"),
            new CountryData("Syrian Arab Republic", R.drawable.flag_syria, "963"),
            new CountryData("Swaziland", R.drawable.flag_swaziland, "268"),
            new CountryData("Turks and Caicos Islands", R.drawable.flag_turks_and_caicos_islands, "1"),
            new CountryData("Chad", R.drawable.flag_chad, "235"),
            new CountryData("Togo", R.drawable.flag_togo, "228"),
            new CountryData("Thailand", R.drawable.flag_thailand, "66"),
            new CountryData("Tajikistan", R.drawable.flag_tajikistan, "992"),
            new CountryData("Tokelau", R.drawable.flag_tokelau, "690"),
            new CountryData("Timor-leste", R.drawable.flag_timor_leste, "670"),
            new CountryData("Turkmenistan", R.drawable.flag_turkmenistan, "993"),
            new CountryData("Tunisia", R.drawable.flag_tunisia, "216"),
            new CountryData("Tonga", R.drawable.flag_tonga, "676"),
            new CountryData("Turkey", R.drawable.flag_turkey, "90"),
            new CountryData("Trinidad", R.drawable.flag_trinidad_and_tobago, "1"),
            new CountryData("Tuvalu", R.drawable.flag_tuvalu, "688"),
            new CountryData("Taiwan", R.drawable.flag_taiwan, "886"),
            new CountryData("Tanzania, United Republic Of", R.drawable.flag_tanzania, "255"),
            new CountryData("Ukraine", R.drawable.flag_ukraine, "380"),
            new CountryData("Uganda", R.drawable.flag_uganda, "256"),
            new CountryData("United States", R.drawable.flag_united_states_of_america, "1"),
            new CountryData("Uruguay", R.drawable.flag_uruguay, "598"),
            new CountryData("Uzbekistan", R.drawable.flag_uzbekistan, "998"),
            new CountryData("Holy See (vatican City State)", R.drawable.flag_vatican_city, "379"),
            new CountryData("Saint Vincent & The Grenadines", R.drawable.flag_saint_vicent_and_the_grenadines, "1"),
            new CountryData("Venezuela, Bolivarian Republic Of", R.drawable.flag_venezuela, "58"),
            new CountryData("British Virgin Islands", R.drawable.flag_british_virgin_islands, "1"),
            new CountryData("US Virgin Islands", R.drawable.flag_us_virgin_islands, "1"),
            new CountryData("Vietnam", R.drawable.flag_vietnam, "84"),
            new CountryData("Vanuatu", R.drawable.flag_vanuatu, "678"),
            new CountryData("Wallis And Futuna", R.drawable.flag_wallis_and_futuna, "681"),
            new CountryData("Kosovo", R.drawable.flag_kosovo, "383"),
            new CountryData("Yemen", R.drawable.flag_yemen, "967"),
            new CountryData("South Africa", R.drawable.flag_south_africa, "27"),
            new CountryData("Zambia", R.drawable.flag_zambia, "260"),
            new CountryData("Zimbabwe", R.drawable.flag_zimbabwe, "263"),

    };
}
